In [26]:
from keras.models import load_model
from MyModel import AL6mA, LA6mA, AL6mA_al, LA6mA_al

In [28]:
model_path = "model/example_model.h5"
m = load_model(model_path)
AL = AL6mA()
LA= LA6mA()
print(m.summary())
print("-----")
print(AL.summary())
print("-----")
print(LA.summary())
print("-----")
print(AL6mA_al().summary())
print("-----")
print(LA6mA_al().summary())

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 41, 4)]      0           []                               
                                                                                                  
 bidirectional_1 (Bidirectional  (None, 41, 32)      9472        ['input_1[0][0]']                
 )                                                                                                
                                                                                                  
 dropout_1 (Dropout)            (None, 41, 32)       0           ['bidirectional_1[0][0]']        
                                                                                                  
 bidirectional_2 (Bidirectional  (None, 41, 32)      16640       ['dropout_1[0][0]']        

In [29]:
from keras.layers.core import Permute
import numpy as np

In [47]:
a = np.arange(5, 10).reshape(-1,1,5)

In [48]:
a

array([[[5, 6, 7, 8, 9]]])

In [50]:
b = Permute((2,1))(a)
b

<tf.Tensor: shape=(1, 5, 1), dtype=int32, numpy=
array([[[5],
        [6],
        [7],
        [8],
        [9]]])>